import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Financer",
  description: "Generated by Fareed Aslam",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />

          <main className="min-h-screen">{children}</main>

          <footer className="bg-white py-6">
            <div className="container mx-auto px-4 text-center ">
              <p>Made With 💗 by Fareed Aslam</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
